### ISSUE TITLE
Implementar zoom nas ilhas

### ISSUE THREAD

**Issue by v1lton** [Henrique1701/Bloomy#39]
Zoom para poder ver melhor os elementos das ilhas

**Comment by Henrique1701** [comment]
- [x] Inserir base de gestos, para o zoom
- [x] Refinar configurações do zoom
- [ ] Realizar testes no iPhone

**Comment by Henrique1701** [comment]
Acho que o zoom já está pronto, mas é preciso realizar mais testes pelo iPhone.

O zoom já foi integrado nesse commit: 1aa0d2f6e8f36a3117bd36e59a610b7a086a8946

**Comment by v1lton** [comment]
Zoom está infinito, chega um momento que a imagem fica pixelada
